
# --- Person ---
person.name.min=2
person.name.max=50
person.lastname.min=2
person.lastname.max=50

# --- Product ---
product.description.max=200
product.price.max=9999999.99

# --- App ---
app.language=es
app.export.delimiter=,
app.export.encoding=UTF-8